### ISSUE TITLE
Requirement of `content-length` breaks on Cloudflare Pages

### ISSUE THREAD

**Issue by ric2b** [phiresky/sql.js-httpvfs#13] opened 2021-06-14 01:16 UTC
Hello, first of all thanks for this super interesting project! It really blew my mind when I read the blog post :)

I'm still just playing around with it and I've been able to get an example based on Svelte Kit working on Github Pages, but on [Cloudflare Pages](https://pages.cloudflare.com/) (which I really prefer) the library breaks because the HEAD request to the sqlite file doesn't return a `content-length` header, triggering this error: https://github.com/phiresky/sql.js-httpvfs/blob/852374bc0fcf84fd7844eadbd1aa074baeee21c9/src/lazyFile.ts#L185

The lack of the header appears to be intentional according to Cloudflare: https://community.cloudflare.com/t/no-content-length-header-when-response-is-compressed/134475

Do you think it would be possible for the library to work without the header, or is it completely impossible/impractical?

**Comment by leonstafford** [comment] 2021-06-14 01:26
This might help soon: https://github.com/cloudflare/cloudflare-docs/issues/841#issuecomment-857847951

From your CF community page thread, modifying the origin response headers may allow the `content-length` to work.

I'm not sure if it's just the guide they're working on or the actual support for custom headers in Pages. From memory, you can do this with a non-Pages Workers/KV site.

**Comment by phiresky** [comment] 2021-06-14 13:02
the content-length is not really required, you can specify the length manually with `fileLength: `. The issue is more that it returns gzip encoding, which is not supported. That might also be something that the server only does for the HEAD request, not for actual GET with Range.

**Comment by ric2b** [comment] 2021-06-14 13:19
It still triggers if I modify my browser's `Accept-Encoding` header to be `identity` instead of `gzip, deflate, br`. And Cloudflare does respect it.

**Comment by phiresky** [comment] 2021-06-14 13:22
Sadly the Accept-Encoding header can't be set from code as far as i know. we can change the error throwing to a warning since i don't think the response headers in the request are indicative of what happens during range request anyways. Also you can disable the conditional that throws the error if this._length is already set (it will be if fileLength is passed as an input)

**Comment by phiresky** [comment] 2021-06-14 13:24
Actually it is a fatal error if content length is not known, so i guess it needs to be split into three conditionals:

1. if !hasByteServing show warning
2. if content encoding is gzip or whatever show warning
3. if content length is not known after the HEAD request throw error

**Comment by ric2b** [comment] 2021-06-15 10:36
Ok, so Cloudflare pages will not be an option until they provide a way to send the `content-length` header.

Thanks for looking into it! :)

**Comment by phiresky** [comment] 2021-06-15 10:47
Maybe I didn't make myself clear, but it is easily possible to use httpvfs
without the server sending the content length header, it just needs a minor
modification to the library as I described above

**Comment by ric2b** [comment] 2021-06-15 11:40
Oh, I misunderstood when you said it was a fatal error, sorry.

I could try to open a PR for this, if you agree. 

Also, I see there are currently no tests on the project, do you have any opinion on adding some, or any preferred test runners, anything like that?

**Comment by phiresky** [comment] 2021-08-23 13:18
This should be fixed with 0.8.10 - I've modified the heuristics as I wrote above.

In addition, I've added a `Range` header to the initial HEAD request, which seems to improve the situation as well (on Netlify at least).

Let me know if you still have issues.

**Closed by phiresky** 2021-08-23 13:18 UTC

**Comment by nooreldeensalah** [comment] 2021-08-29 13:23
Hi @ric2b,

Sorry for the off-topic comment, but I've also been trying to get the library to work with sveltekit, but I've been getting errors so far, I've managed to get it to work with svelte using the webpack template, but I want to use it with sveltekit for more flexibility.

I would appreciate your help.

Thanks,

**Comment by kidGodzilla** [comment] 2022-01-02 07:32
I found an interesting workaround for this when searching for a solution to this problem on Netlify, in their forums.

I simply renamed the file to `database.sqlite3.png`. Since the extension is arbitrary, you may be able to find a file extension that is treated differently by Cloudflare Pages. Certainly, audio and video would work, if it's looking at extensions vs. mime types.

**Comment by johtso** [comment] 2022-04-09 12:58
Has anyone managed to get this working on cloudflare pages?

I'm getting `Warning: The server did not respond with Accept-Ranges=bytes`
..and then cloudflare is responding with the full database instead of just the range.

![image](https://user-images.githubusercontent.com/830800/162575079-50045f21-d18d-451d-8664-3b6635b7aa53.png)

..which then results in `SQLite: database disk image is malformed`

I also see lots of posts on their forums complaining about lack of range support.

**Comment by phiresky** [comment] 2022-04-09 13:43
The hack posted by kidGodzilla might also work for cloudflare pages if you use an extension like mp4,mp3,... where they are more likely to accept byte ranges. if not then it's not going to be possible

**Comment by johtso** [comment] 2022-04-09 13:51
@phiresky may as well give it a go. Not sure if it's currently possible to add an extension when chunking the database?

**Comment by phiresky** [comment] 2022-04-09 13:55
I'm not sure. Shouldn't be easy to change if it actually works, but that article sounds like it won't
